/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArtWritingRouteImport } from './routes/art-writing'
import { Route as BooksRouteImport } from './routes/books'
import { Route as KalpaSagaRouteImport } from './routes/kalpa-saga'
import { Route as PovRouteImport } from './routes/pov'
import { Route as TechWorkRouteImport } from './routes/tech-work'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtWritingRoute = ArtWritingRouteImport.update({
  id: '/art-writing',
  path: '/art-writing',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksRoute = BooksRouteImport.update({
  id: '/books',
  path: '/books',
  getParentRoute: () => rootRouteImport,
} as any)
const KalpaSagaRoute = KalpaSagaRouteImport.update({
  id: '/kalpa-saga',
  path: '/kalpa-saga',
  getParentRoute: () => rootRouteImport,
} as any)
const PovRoute = PovRouteImport.update({
  id: '/pov',
  path: '/pov',
  getParentRoute: () => rootRouteImport,
} as any)
const TechWorkRoute = TechWorkRouteImport.update({
  id: '/tech-work',
  path: '/tech-work',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/art-writing': typeof ArtWritingRoute
  '/books': typeof BooksRoute
  '/kalpa-saga': typeof KalpaSagaRoute
  '/pov': typeof PovRoute
  '/tech-work': typeof TechWorkRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/art-writing': typeof ArtWritingRoute
  '/books': typeof BooksRoute
  '/kalpa-saga': typeof KalpaSagaRoute
  '/pov': typeof PovRoute
  '/tech-work': typeof TechWorkRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/art-writing': typeof ArtWritingRoute
  '/books': typeof BooksRoute
  '/kalpa-saga': typeof KalpaSagaRoute
  '/pov': typeof PovRoute
  '/tech-work': typeof TechWorkRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/art-writing' | '/books' | '/kalpa-saga' | '/pov' | '/tech-work'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/art-writing' | '/books' | '/kalpa-saga' | '/pov' | '/tech-work'
  id:
    | '__root__'
    | '/'
    | '/art-writing'
    | '/books'
    | '/kalpa-saga'
    | '/pov'
    | '/tech-work'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArtWritingRoute: typeof ArtWritingRoute
  BooksRoute: typeof BooksRoute
  KalpaSagaRoute: typeof KalpaSagaRoute
  PovRoute: typeof PovRoute
  TechWorkRoute: typeof TechWorkRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/art-writing': {
      id: '/art-writing'
      path: '/art-writing'
      fullPath: '/art-writing'
      preLoaderRoute: typeof ArtWritingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books': {
      id: '/books'
      path: '/books'
      fullPath: '/books'
      preLoaderRoute: typeof BooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kalpa-saga': {
      id: '/kalpa-saga'
      path: '/kalpa-saga'
      fullPath: '/kalpa-saga'
      preLoaderRoute: typeof KalpaSagaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pov': {
      id: '/pov'
      path: '/pov'
      fullPath: '/pov'
      preLoaderRoute: typeof PovRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tech-work': {
      id: '/tech-work'
      path: '/tech-work'
      fullPath: '/tech-work'
      preLoaderRoute: typeof TechWorkRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArtWritingRoute: ArtWritingRoute,
  BooksRoute: BooksRoute,
  KalpaSagaRoute: KalpaSagaRoute,
  PovRoute: PovRoute,
  TechWorkRoute: TechWorkRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
